[package]
name = "swarm-weave"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
tokio-macros = "2.4.0"

[dependencies.clap]
version = "4.5.3"
features = [
    "derive",
    "color"
]

[dependencies.tokio]
version = "1.39.2"
features = ["full"]
