//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "debug-property-image-upload")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_name = "actionCourseUuid")]
    pub action_course_uuid: String,
    #[sea_orm(column_name = "actionStage")]
    pub action_stage: i16,
    pub action: Option<String>,
    #[sea_orm(column_name = "imageNames")]
    pub image_names: Option<Json>,
    pub title: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub status: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
