//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "group-app-junction")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_name = "appName")]
    pub app_name: String,
    #[sea_orm(column_name = "groupId")]
    pub group_id: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app::Entity",
        from = "Column::AppName",
        to = "super::app::Column::Name",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    App,
    #[sea_orm(
        belongs_to = "super::app_group::Entity",
        from = "Column::GroupId",
        to = "super::app_group::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppGroup,
}

impl Related<super::app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::App.def()
    }
}

impl Related<super::app_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
