//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "listening-to")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "musicId")]
    pub music_id: Option<i64>,
    #[sea_orm(column_name = "personalLogId")]
    pub personal_log_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::music::Entity",
        from = "Column::MusicId",
        to = "super::music::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Music,
    #[sea_orm(
        belongs_to = "super::personal_log::Entity",
        from = "Column::PersonalLogId",
        to = "super::personal_log::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    PersonalLog,
}

impl Related<super::music::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Music.def()
    }
}

impl Related<super::personal_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonalLog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
