//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "personal-log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_name = "timeAccurate")]
    pub time_accurate: i8,
    pub start: DateTime,
    pub r#type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub details: Option<Json>,
    pub mixed: Option<i8>,
    pub links: Option<Json>,
    pub references: Option<Json>,
    pub tags: Option<Json>,
    #[sea_orm(column_name = "untilTimeAccurate")]
    pub until_time_accurate: i8,
    pub until: Option<DateTime>,
    pub updated: Option<DateTime>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: Option<DateTime>,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: Option<DateTime>,
    #[sea_orm(column_name = "addressId")]
    pub address_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::address::Entity",
        from = "Column::AddressId",
        to = "super::address::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Address,
    #[sea_orm(has_many = "super::listening_to::Entity")]
    ListeningTo,
    #[sea_orm(has_many = "super::log_notes::Entity")]
    LogNotes,
}

impl Related<super::address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Address.def()
    }
}

impl Related<super::listening_to::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ListeningTo.def()
    }
}

impl Related<super::log_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LogNotes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
