//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "Online")]
    Online,
    #[sea_orm(string_value = "Offline")]
    Offline,
    #[sea_orm(string_value = "Maintenance")]
    Maintenance,
}
