//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "system-resources")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_name = "evalTime")]
    pub eval_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::server_node::Entity")]
    ServerNode,
    #[sea_orm(has_many = "super::storage_device::Entity")]
    StorageDevice,
    #[sea_orm(has_many = "super::system_core::Entity")]
    SystemCore,
    #[sea_orm(has_many = "super::system_memory::Entity")]
    SystemMemory,
}

impl Related<super::server_node::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServerNode.def()
    }
}

impl Related<super::storage_device::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StorageDevice.def()
    }
}

impl Related<super::system_core::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemCore.def()
    }
}

impl Related<super::system_memory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SystemMemory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
